#!/usr/bin/env bash
source $(dirname $0)/description
source $(dirname $0)/testflow
source $(dirname $0)/feature

# Initialize Notepack.
#
# Creates files and folders for the root directory of the app in the directory
# where the app is placed.
#
init_root()
{
  mkdir -p ./tickets/
  mkdir -p ./features/
  mkdir -p ./config/
}


# New Notepack.
#
# Creates files and folders for a new notepack for a specific ticket.
#
new_notepack()
{
  echo -e "\e[96mCreating folders and initializing files"
  mkdir -p "$CURRENT_TICKET_PATH"/testflows
  mkdir -p "$CURRENT_TICKET_PATH"/pictures
  mkdir -p "$CURRENT_TICKET_PATH"/scripts
  new_description
  new_testflow
  echo -e "\e[96mDone!"
}


# Edit Ticket.
#
# Opens the description.md and the newest testflow_mk.md with vim
#
edit_notepack()
{
  local newest_testflow=$(ls $CURRENT_TICKET_PATH/testflows \
                          | sort -r \
                          | head -n 1)
  exec vim -p $CURRENT_TICKET_PATH/description.md \
              $CURRENT_TICKET_PATH/testflows/$newest_testflow
}


# Show Help Menu.
#
# Show usage menu. To be used any time an error occurs.
#
show_help_menu() {
  echo "
    Usage: notepack [OPTION]... [TICKET_NAME]...
    Notepack App. Create folder structures and files for writing testflow notes
    and prototypes.

    --new-ticket      Creates new Notepack package with given ticket name.
    --edit-ticket     Opens the description and newest testflow for editing.
    --new-testflow    Creates a new test for given ticket name.
    --init            Creates root folders for the app.
    --help            Shows this menu.
  "
}


# Configuration ###############################################################
# Global Paths.
CONFIG_PATH="./config"
TICKET_PATH="./tickets"
FEATURES_PATH="./features"


# Main Script #################################################################
# Global Variables.
action="$1"

# Handle new ticket name vs directory and extract ticket name.
if [[ -d "$2" ]]; then
  ticket_name=$(echo "$2" | cut -d'/' -f2 )
else
  ticket_name="$2"
fi

CURRENT_TICKET_PATH="$TICKET_PATH/$ticket_name"
CURRENT_TICKET_TESTFLOWS="$TICKET_PATH/$ticket_name/testflows"

# Process arguments. Mostly create new notepack or testflow or init app.
case "$action" in
  "--init") init_root ;;
  "--new-ticket") new_notepack ;;
  "--edit-ticket") edit_notepack;;
  "--new-testflow") new_testflow ;;
  * | "--help") show_help_menu ;;
esac

exit 0
