#!/usr/bin/env bash

# New Testflow.
#
# Creates a testflow testfile with a new mk# and file structure.
#
new_testflow()
{
  local last_mk=$(get_last_testflow)
  new_testflow="testflow_mk$((last_mk+=1)).md"

  cp "$CONFIG_PATH"/testflow.md "$CURRENT_TICKET_TESTFLOWS"/"$new_testflow"
}


# Last Testflow Number.
#
# Look through the testflows folder for the last mk#.
#
get_last_testflow()
{
  # Check if there are already testflows. If none, create first.
  local existing_testflows=$(ls $CURRENT_TICKET_TESTFLOWS | wc -l)
  # local last_mk=$(ls $CURRENT_TICKET_TESTFLOWS \
  #                 | sort -r -n -t _ -k 2 \
  #                 | head -n 1 \
  #                 | sed 's/[^0-9]//g')
  echo $existing_testflows
}

