#!/usr/bin/env bash

# Initialize App
#
# Creates files and folders for the root directory of the app in the directory
# where the app is placed.
#
init_root()
{
  mkdir -p ./tickets/
  mkdir -p ./features/
  mkdir -p ./config/
}


# New Notepack.
#
# Creates files and folders for a new notepack for a specific ticket.
# @param  $1  ticket_path
#
new_notepack()
{
  # Create initial directories for the new notepack.
  echo -e "\e[96mCreating folders and initializing files"
  mkdir -p "$1"/testflows
  mkdir -p "$1"/pictures
  mkdir -p "$1"/scripts

  # Add default documents from the config file to the new notepack.
  new_description
  new_testflow

  # Conclude operations and open the notepack in vim.
  echo -e "\e[96mDone!"
  edit_notepack
}


# Edit Ticket.
#
# Opens the description.md and the newest testflow_mk.md with vim
# @param  $1  ticket_path
#
edit_notepack()
{
  local newest_testflow=$(ls $1/testflows \
                          | sort -r \
                          | head -n 1)
  exec vim -p $1/description.md \
              $1/testflows/$newest_testflow
}


