#!/usr/bin/env bash
# Ticket
# Functions to manipulate directories for tickets, including creating the
# ticket's root directories and default documentation templates.
#


# New Ticket
# Creates files and folders for a new notepack for a specific ticket.
# @param  $1  config_path
# @param  $2  ticket_path
#
new_ticket()
{
  local config_path="$1"
  local ticket_path="$2"

  # Create initial directories for the new notepack.
  echo -e "\e[96mCreating folders and initializing files"
  mkdir -p "$ticket_path"/testflows
  mkdir -p "$ticket_path"/pictures
  mkdir -p "$ticket_path"/scripts

  # Add default documents from the config file to the new notepack.
  new_description $config_path $ticket_path
  new_testflow $config_path $ticket_path
  new_testing_story $config_path $ticket_path
  new_test_summary $config_path $ticket_path

  # Conclude operations and open the notepack in vim.
  echo -e "\e[96mDone!"
  edit_ticket $ticket_path
}


# Edit Ticket
# Opens the description.md and the newest testflow_mk.md with vim.
# @param  $1  ticket_path
#
edit_ticket()
{
  local ticket_path="$1"

  local newest_testflow=$(ls "$ticket_path"/testflows \
                          | sort -r \
                          | head -n 1)
  exec vim -p "$ticket_path"/description.md \
              "$ticket_path"/testflows/$newest_testflow \
              "$ticket_path"/testing_story.md
}


